name: test-clang-format

on: [push, pull_request]

jobs:
  c_style_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: '.'
        # exclude: './third_party ./external'
        extensions: 'c,h,cpp,hpp'
        clangFormatVersion: 14
        style: llvm
  cmake-format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - run: |
        python -m pip install --upgrade pip
        pip3 install cmake-format
        cmake-format -i CMakeLists.txt       
        git --no-pager diff --exit-code -- CMakeLists.txt